### ISSUE TITLE
Selecting Multiple Options

### ISSUE THREAD

**Issue by paulmolluzzo** [captainsafia/goops#1]
This is a helpful tool, thanks!

For some projects I might have a few things in the stack that have different items to ignore, but the current implementation only allows me to select one of the options at a time (and you have to know to re-run `goops` to for each possible "type" of `.gitignore` to add). It would be great to:

1. Allow multiple selections, probably by comma delimiting them.
2. Allow some "Select All" option.

Thoughts?

**Comment by captainsafia** [comment]
Hi, @paulmolluzzo! Thanks for opening this issue!

I foresaw this when I released the tool but wanted to make sure that I wasn't the only person who thought this. I can probably have this implemented sometime this weekend for the next minor release.

Glad you like goops!

**Comment by paulmolluzzo** [comment]
I can get a PR to you in a few minutes if you like. 😄

**Comment by captainsafia** [comment]
Even better! Thanks!

**Comment by paulmolluzzo** [comment]
Writing up the PR now!
