### ISSUE TITLE
gitignores are git ignored

### ISSUE THREAD

**Issue by cookiengineer** [captainsafia/goops#4]
[This variable](https://github.com/captainsafia/goops/blob/master/src/get-gitignore.js#L10) will be empty, because the `/.gitignore` file of this repository does not allow the `/gitignores` folder to be added / pushed.

Is that on purpose or does this project intend to not ship any templates?

**Comment by captainsafia** [comment]
This is on purpose! [On install](https://github.com/captainsafia/goops/blob/master/package.json#L10), this project downloads the gitignores. I suppose I should add a note that you'll need to run `npm run postinstall` if you're working in development mode as well.
